pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\clients\clients.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\clients\hey.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\clients\schol2.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\clients\sherston.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\logo\app_store_badge.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\logo\dog.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\logo\jali.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\logo\logo.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\createanddisplay\slide1.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\createanddisplay\slide2.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\createanddisplay\slide3.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\createanddisplay\slide4.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\datahandling\slide1.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\datahandling\slide2.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\datahandling\slide3.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\datahandling\slide4.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\fastest\slide1.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\fastest\slide2.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\fastest\slide3.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\fastest\slide4.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\fastest\slide5.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\fastest\slide6.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hmfs\slide1.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hmfs\slide2.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hmfs\slide3.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hmfs\slide4.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hmfs\slide5.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hmfs\slide6.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hmfs\slide7.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hmfs\slide8.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hottopics\slide1.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hottopics\slide10.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hottopics\slide11.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hottopics\slide2.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hottopics\slide3.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hottopics\slide4.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hottopics\slide6.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hottopics\slide7.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hottopics\slide8.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\hottopics\slide9.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\maryg\slide1.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\maryg\slide2.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\maryg\slide3.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\mathsreaders\slide1.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\rtm\slide1.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\rtm\slide10.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\rtm\slide11.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\rtm\slide12.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\rtm\slide13.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\rtm\slide2.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\rtm\slide3.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\rtm\slide4.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\rtm\slide5.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\rtm\slide6.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\rtm\slide7.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\rtm\slide8.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\rtm\slide9.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\shockwaves\slide1.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\shockwaves\slide2.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\shockwaves\slide4.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\shockwaves\slide5.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\shockwaves\slide6.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\slide\shockwaves\slide7.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\video\video1.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\video\video2.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\workother\connect4_screen4.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\workother\iching3.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\workother\lego1.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\workother\lego2.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\workother\lego3.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\workother\logo1.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\workother\logo2.png
pngquant 192 --force --ext .png D:\Documents\website\stormy-thicket-1299\public\img\workother\logo3.png
